OPTIONS (SKIP = 1)
LOAD DATA
 INFILE '../data/equipos.csv'
 INTO TABLE EQUIPOS
 FIELDS TERMINATED BY ';'
 ( 
    NOMBRECORTO, 
    NOMBREOFICIAL, 
    CIUDAD, 
    FECHAFUNDACION, 
    FECHALEGAL, 
    NOMBREHISTORICO, 
    NOMESTADIO
)