DROP TABLE PARTIDOS;

DROP TABLE OTROS_NOMBRES;

DROP TABLE JORNADAS;

DROP TABLE EQUIPOS  CASCADE CONSTRAINTS;

DROP TABLE ESTADIOS CASCADE CONSTRAINTS;

DROP TABLE TEMPORADAS;

DROP TABLE DIVISIONES;
DROP TABLE EQUIPOL CASCADE CONSTRAINTS;
DROP TABLE EQUIPOV CASCADE CONSTRAINTS;

